// 05-React/counter/src/Counter.js
import { useState } from 'react';

function Counter() {
  console.log('Counter actice...');
  const [count, setCount] = useState(0);

  const inc = () => {
    setCount(count + 1);
    console.log(count);
  };

  return (
    <>
      Counter: {count}<br />
      <button onClick={inc}>increment</button>
    </>
  );
}

export default Counter;

// 04-Angular/signal-demos/src/counter.component.ts
import { Component, effect, Input, WritableSignal } from '@angular/core';

@Component({
  selector: 'app-counter',
  standalone: true,
  template: `
    <div>
      <h2>Count: {{ count() }}</h2>
      <button (click)="increment()">+</button>
    </div>
  `
})
export class CounterComponent {
  @Input() count!: WritableSignal<number>;
  
  constructor() {
    effect(() => {
      console.log('Count changed:', this.count());
    });
  }
  
  increment() {
    this.count.update((n: number) => n + 1);
  }
}
