// 04-Angular/angular-dashboard-solution/src/app/components/login/login-form.component.ts
import { Component } from '@angular/core';
import { AuthService } from '../../services/auth.service';
import { Router } from '@angular/router';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-login-form',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './login-form.component.html',
})
export class LoginFormComponent {
  email: string = 'user@mail.com';
  password: string = '123456';
  errorMessage: string = '';

  constructor(private authService: AuthService, private router: Router) {}

  authenticate() {
    this.authService.login(this.email, this.password).subscribe((ok) => {
      if (ok) {
        this.router.navigate(['dashboard']);
      } else {
        this.errorMessage = 'Something went wrong.';
      }
    });
  }
}
<div class="space-y-3">
  <div class="flex-1 rounded-lg bg-gray-50 px-6 pb-4 pt-8">
    <h1 class="mb-3 text-2xl">Please log in to continue.</h1>
    <div class="w-full">
      <div>
        <label
          class="mb-3 mt-5 block text-xs font-medium text-gray-900"
          for="email"
        >
          Email
        </label>
        <div class="relative">
          <input
            class="peer block w-full rounded-md border border-gray-200 py-[9px] pl-10 text-sm outline-2 placeholder:text-gray-500"
            id="email"
            type="email"
            name="email"
            [(ngModel)]="email"
            placeholder="Enter your email address"
            required
          />
          <span class="material-symbols-outlined pointer-events-none absolute left-3 top-1/2 h-[18px] w-[18px] -translate-y-1/2 text-gray-500 peer-focus:text-gray-900">alternate_email</span>
        </div>
      </div>
      <div class="mt-4">
        <label
          class="mb-3 mt-5 block text-xs font-medium text-gray-900"
          for="password"
        >
          Password
        </label>
        <div class="relative">
          <input
            class="peer block w-full rounded-md border border-gray-200 py-[9px] pl-10 text-sm outline-2 placeholder:text-gray-500"
            id="password"
            type="password"
            name="password"
            placeholder="Enter password"
            [(ngModel)]="password"
            required
            minLength="6"
          />
          <span class="material-symbols-outlined pointer-events-none absolute left-3 top-1/2 h-[18px] w-[18px] -translate-y-1/2 text-gray-500 peer-focus:text-gray-900">key</span>
        </div>
      </div>
    </div>
    <button
      class="flex h-10 items-center rounded-lg bg-blue-500 px-4 text-sm font-medium text-white transition-colors hover:bg-blue-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-500 active:bg-blue-600 aria-disabled:cursor-not-allowed aria-disabled:opacity-50 mt-4 w-full"
      (click)="authenticate()"
    >
      Log in
      <span class="material-symbols-outlined ml-auto h-5 w-5 text-gray-50">arrow_right_alt</span>
    </button>
    <div
      class="flex h-8 items-end space-x-1"
      aria-live="polite"
      aria-atomic="true"
    >
      <p class="text-sm text-red-500">{{ errorMessage }}</p>
    </div>
  </div>
</div>

// 06-NextJS/nextjs-example-solution/app/ui/login-form.tsx
'use client';
 
import {
  AtSymbolIcon,
  KeyIcon,
  ExclamationCircleIcon,
} from '@heroicons/react/24/outline';
import { ArrowRightIcon } from '@heroicons/react/20/solid';
import { Button } from '@/app/ui/button';
import { useActionState } from 'react';
import { authenticate } from '@/app/lib/actions';
 
export default function LoginForm() {
  const [errorMessage, formAction, isPending] = useActionState(
    authenticate,
    undefined,
  );
 
  return (
    <form action={formAction} className="space-y-3">
      <div className="flex-1 rounded-lg bg-gray-50 px-6 pb-4 pt-8">
        <h1 className={`mb-3 text-2xl`}>
          Please log in to continue.
        </h1>
        <div className="w-full">
          <div>
            <label
              className="mb-3 mt-5 block text-xs font-medium text-gray-900"
              htmlFor="email"
            >
              Email
            </label>
            <div className="relative">
              <input
                className="peer block w-full rounded-md border border-gray-200 py-[9px] pl-10 text-sm outline-2 placeholder:text-gray-500"
                id="email"
                type="email"
                name="email"
                placeholder="Enter your email address"
                required
              />
              <AtSymbolIcon className="pointer-events-none absolute left-3 top-1/2 h-[18px] w-[18px] -translate-y-1/2 text-gray-500 peer-focus:text-gray-900" />
            </div>
          </div>
          <div className="mt-4">
            <label
              className="mb-3 mt-5 block text-xs font-medium text-gray-900"
              htmlFor="password"
            >
              Password
            </label>
            <div className="relative">
              <input
                className="peer block w-full rounded-md border border-gray-200 py-[9px] pl-10 text-sm outline-2 placeholder:text-gray-500"
                id="password"
                type="password"
                name="password"
                placeholder="Enter password"
                required
                minLength={6}
              />
              <KeyIcon className="pointer-events-none absolute left-3 top-1/2 h-[18px] w-[18px] -translate-y-1/2 text-gray-500 peer-focus:text-gray-900" />
            </div>
          </div>
        </div>
        <Button className="mt-4 w-full" aria-disabled={isPending}>
          Log in <ArrowRightIcon className="ml-auto h-5 w-5 text-gray-50" />
        </Button>
        <div
          className="flex h-8 items-end space-x-1"
          aria-live="polite"
          aria-atomic="true"
        >
          {errorMessage && (
            <>
              <ExclamationCircleIcon className="h-5 w-5 text-red-500" />
              <p className="text-sm text-red-500">{errorMessage}</p>
            </>
          )}
        </div>
      </div>
    </form>
  );
}
