// 04-Angular/angular-dashboard-solution/src/app/components/shared/pagination/pagination.component.ts
import { Component, Input, OnChanges, SimpleChanges } from '@angular/core';
import { SubscriptionService } from '../../../services/subscription.service';
import { NgClass } from '@angular/common';
import { generatePagination } from '../../../utils';

@Component({
  selector: 'app-pagination',
  standalone: true,
  imports: [NgClass],
  templateUrl: './pagination.component.html',
})
export class PaginationComponent implements OnChanges {
  @Input() totalPages!: number;
  @Input() currentPage!: number;

  Number = Number; // make Number operator usable in template

  pages: (string | number)[] = [];

  constructor(private subscriptionService: SubscriptionService) {
  }

  ngOnChanges(changes: SimpleChanges): void {
    console.log(`changes: ${JSON.stringify(changes)}`);
    this.pages = generatePagination(this.currentPage, this.totalPages);
  }

  arrowClasses(direction: 'left' | 'right', isDisabled: boolean): string {
    let classes = 'material-symbols-outlined flex h-10 w-10 items-center justify-center rounded-md border';
    classes += direction === 'left' ? ' mr-2 md:mr-4' : ' ml-2 md:ml-4';
    classes += isDisabled ? ' pointer-events-none text-gray-300' : ' hover:bg-gray-100';
    return classes;
  }

  numberClasses(page: number | string, index: number): string {
    let position: 'first' | 'last' | 'single' | 'middle' | undefined;
    let isActive = this.currentPage === page;

    if (index === 0)
      position = 'first';
    if (index === this.pages.length - 1)
      position = 'last';
    if (this.pages.length === 1)
      position = 'single';
    if (page === '...')
      position = 'middle';

    let classes = 'flex h-10 w-10 items-center justify-center text-sm border';
    if (position === 'first' || position === 'single') {
      classes += ' rounded-l-md';
    }
    if (position === 'last' || position === 'single') {
      classes += ' rounded-r-md';
    }
    if (isActive) {
      classes += ' z-10 bg-blue-600 border-blue-600 text-white';
    }
    if (!isActive && position !== 'middle') {
      classes += ' hover:bg-gray-100';
    }
    if (position === 'middle') {
      classes += ' text-gray-300';
    }

    return classes;
  }

  gotoPage(page: number, isDisabled: boolean) {
    if (!isDisabled)
      this.subscriptionService.updateCurrentPage(page);
  }
}
<div class="inline-flex">
  <!-- arrow left -->
  <a (click)="gotoPage(currentPage - 1, currentPage <= 1)">
    <span [ngClass]="arrowClasses('left', currentPage <= 1)">arrow_back</span>
  </a>

  <div class="flex -space-x-px">
    @for (page of pages; track page; let i = $index) {
      <a
        [ngClass]="numberClasses(page, i)"
        (click)="gotoPage(Number(page), currentPage === Number(page))">
        {{page}}
      </a>
    }
  </div>

  <!-- right arrow -->
  <a (click)="gotoPage(currentPage + 1, currentPage >= totalPages)">
    <span [ngClass]="arrowClasses('right', currentPage >= totalPages)">
      arrow_forward
    </span>
  </a>
</div>

// 06-NextJS/nextjs-example-exercise/app/ui/invoices/pagination.tsx
'use client';

import { ArrowLeftIcon, ArrowRightIcon } from '@heroicons/react/24/outline';
import clsx from 'clsx';
import Link from 'next/link';
import { generatePagination } from '@/app/lib/utils';
import { usePathname, useSearchParams } from 'next/navigation';

export default function Pagination({ totalPages }: { totalPages: number }) {
  const pathname = usePathname();
  const searchParams = useSearchParams();
  const currentPage = Number(searchParams.get('page')) || 1;
  const allPages = generatePagination(currentPage, totalPages);

  const createPageURL = (pageNumber: number | string) => {
    const params = new URLSearchParams(searchParams);
    params.set('page', pageNumber.toString());
    return `${pathname}?${params.toString()}`;
  };
  
  return (
    <>
      {<div className="inline-flex">
        <PaginationArrow
          direction="left"
          href={createPageURL(currentPage - 1)}
          isDisabled={currentPage <= 1}
        />

        <div className="flex -space-x-px">
          {allPages.map((page, index) => {
            let position: 'first' | 'last' | 'single' | 'middle' | undefined;

            if (index === 0) position = 'first';
            if (index === allPages.length - 1) position = 'last';
            if (allPages.length === 1) position = 'single';
            if (page === '...') position = 'middle';

            return (
              <PaginationNumber
                key={page}
                href={createPageURL(page)}
                page={page}
                position={position}
                isActive={currentPage === page}
              />
            );
          })}
        </div>

        <PaginationArrow
          direction="right"
          href={createPageURL(currentPage + 1)}
          isDisabled={currentPage >= totalPages}
        />
      </div>}
    </>
  );
}

function PaginationNumber({
  page,
  href,
  isActive,
  position,
}: {
  page: number | string;
  href: string;
  position?: 'first' | 'last' | 'middle' | 'single';
  isActive: boolean;
}) {
  const className = clsx(
    'flex h-10 w-10 items-center justify-center text-sm border',
    {
      'rounded-l-md': position === 'first' || position === 'single',
      'rounded-r-md': position === 'last' || position === 'single',
      'z-10 bg-blue-600 border-blue-600 text-white': isActive,
      'hover:bg-gray-100': !isActive && position !== 'middle',
      'text-gray-300': position === 'middle',
    },
  );

  return isActive || position === 'middle' ? (
    <div className={className}>{page}</div>
  ) : (
    <Link href={href} className={className}>
      {page}
    </Link>
  );
}

function PaginationArrow({
  href,
  direction,
  isDisabled,
}: {
  href: string;
  direction: 'left' | 'right';
  isDisabled?: boolean;
}) {
  const className = clsx(
    'flex h-10 w-10 items-center justify-center rounded-md border',
    {
      'pointer-events-none text-gray-300': isDisabled,
      'hover:bg-gray-100': !isDisabled,
      'mr-2 md:mr-4': direction === 'left',
      'ml-2 md:ml-4': direction === 'right',
    },
  );

  const icon =
    direction === 'left' ? (
      <ArrowLeftIcon className="w-4" />
    ) : (
      <ArrowRightIcon className="w-4" />
    );

  return isDisabled ? (
    <div className={className}>{icon}</div>
  ) : (
    <Link className={className} href={href}>
      {icon}
    </Link>
  );
}
