// 07-docker/react-dev/order-client/src/components/OrderList.jsx
import './OrderList.css'
import { Trash2 } from 'lucide-react';

function formatCurrency(val) {
  return val.toLocaleString('en', {
    style: 'currency',
    currency: 'EUR'
  });
}

function OrderList({ orders, deleteOrder }) {
  const total = (order) => {
    return formatCurrency(order.positions.reduce((sum, p) => sum + p.amount*p.price, 0));
  }

  if (orders.length === 0) 
    return <p>No orders yet.</p>;

  return (
    <div className="order-list">
      {orders.map(order => (
        <div key={order.id} className="order-card">
          <h2>Order #{order.id}</h2>
          <button type="button" className="delete-button" onClick={e => deleteOrder(order)}>
            <Trash2 size={24} />
          </button>
          <p><strong>Customer:</strong> {order.customer}</p>
          <p><strong>Date:</strong> {new Date(Number(order.date)).toLocaleString()}</p>
          <p><strong>Total:</strong> {total(order)}</p>
          <ul>
            {order.positions.map((p, i) => (
              <li key={i}>
                #{p.number} {p.article}: {p.amount} x {formatCurrency(p.price)} = {formatCurrency(p.amount * p.price)}  
              </li>
            ))}
          </ul>
        </div>
      ))}
    </div>
  )
}

export default OrderList

// 07-docker/angular-dev/order-client/src/app/components/order-list/order-list.ts
import { Component, Input, WritableSignal } from '@angular/core';
import { Order } from '../../models/Order';
import { Server } from '../../services/server';
import { MatIcon } from '@angular/material/icon';

@Component({
  selector: 'app-order-list',
  imports: [MatIcon],
  standalone: true,
  templateUrl: './order-list.html',
  styleUrl: './order-list.css'
})
export class OrderList {
  @Input() orders!: WritableSignal<Order[]>;

  constructor(private server: Server) {
  }

  public formatCurrency(val: number): string {
    return val.toLocaleString('en', {
      style: 'currency',
      currency: 'EUR'
    });
  }
  public total(order: Order): string {
    return this.formatCurrency(order.positions.reduce((sum, p) => sum + p.amount*p.price, 0));
  }

  public formatOrderDate(order: Order): string {
    return new Date(Number(order.date)).toLocaleString();
  }

  public deleteOrder(order: Order): void {
    this.server.deleteOrder(order.id)
    .subscribe(_ => {
      this.orders.update(arr => this.orders().filter(o => o.id !== order.id));
    });
  }
}
