// 06-NextJS/nextjs-example-solution/app/ui/dashboard/latest-invoices.tsx
import { ArrowPathIcon } from '@heroicons/react/24/outline';
import clsx from 'clsx';
import Image from 'next/image';
import { LatestInvoice } from '@/app/lib/definitions';
import { formatDateToLocal } from '@/app/lib/utils';
import { fetchLatestInvoices } from '@/app/lib/data';

export default async function LatestInvoices() {
  const latestInvoices: LatestInvoice[] = await fetchLatestInvoices();

  return (
    <div className="flex w-full flex-col md:col-span-4">
      <h2 className={`mb-4 text-xl md:text-2xl`}>
        Latest Invoices
      </h2>
      <div className="flex grow flex-col justify-between rounded-xl bg-gray-50 p-4">
        {<div className="bg-white px-6">
          {latestInvoices.map((invoice, i) => {
            return (
              <div
                key={invoice.id}
                className={clsx(
                  'flex flex-row items-center justify-between py-4',
                  {
                    'border-t': i !== 0,
                  },
                )}
              >
                <div className="flex items-center">
                  <Image
                    src={invoice.image_url}
                    alt={`${invoice.name}'s profile picture`}
                    className="mr-4 rounded-full"
                    width={32}
                    height={32}
                  />
                  <div className="min-w-0">
                    <p className="truncate text-sm font-semibold md:text-base">
                      {invoice.name}
                    </p>
                    <p className="hidden text-sm text-gray-500 sm:block">
                      {invoice.email}
                    </p>
                    <p className="hidden text-sm text-gray-500 sm:block">
                      {formatDateToLocal(invoice.date, 'de-de')}
                    </p>
                  </div>
                </div>
                <p
                  className={`truncate text-sm font-medium md:text-base`}
                >
                  {invoice.amount}
                </p>
              </div>
            );
          })}
        </div>}
        <div className="flex items-center pb-2 pt-6">
          <ArrowPathIcon className="h-5 w-5 text-gray-500" />
          <h3 className="ml-2 text-sm text-gray-500 ">Updated just now</h3>
        </div>
      </div>
    </div>
  );
}

// 04-Angular/angular-dashboard-solution/src/app/components/dashboard/dashboard-home/latest-invoices/latest-invoices.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { LatestInvoice } from '../../../../models/LatestInvoice';

import { BackendService } from '../../../../services/backend.service';
import { formatDateToLocal } from '../../../../utils';
import { SkeletonComponent } from "../../../shared/skeleton/skeleton.component";

@Component({
  selector: 'app-latest-invoices',
  standalone: true,
  imports: [SkeletonComponent],
  templateUrl: './latest-invoices.component.html',
})
export class LatestInvoicesComponent {
  latestInvoices: LatestInvoice[] = [];
  loading: boolean;

  constructor(private backendService: BackendService) {
    this.loading = true;
    this.backendService.fetchLatestInvoices()
    .subscribe(invoices => {
      this.latestInvoices = invoices;
      this.loading = false;
    });
  }

  formatDate(date: string, locale: string) {
    return formatDateToLocal(date, locale);
  }

}
@if (!loading) {
  <div>
    <div class="flex w-full flex-col md:col-span-4">
      <h2 class="mb-4 text-xl md:text-2xl">
        Latest Invoices
      </h2>
      <div class="flex grow flex-col justify-between rounded-xl bg-gray-50 p-4">
        <div class="bg-white px-6">
          @for (invoice of latestInvoices; track invoice; let i = $index) {
            <div
              class="flex flex-row items-center justify-between py-4 border-t">
              <div class="flex items-center">
                <img src={{invoice.image_url}}
                  [alt]="invoice.name" class="mr-4 rounded-full"  width="32" height="32"/>
                <div class="min-w-0">
                  <p class="truncate text-sm font-semibold md:text-base">
                    {{invoice.name}}
                  </p>
                  <p class="hidden text-sm text-gray-500 sm:block">
                    {{invoice.email}}
                  </p>
                  <p class="hidden text-sm text-gray-500 sm:block">
                    {{formatDate(invoice.date, 'de-de')}}
                  </p>
                </div>
              </div>
              <p class="truncate text-sm font-medium md:text-base">
                {{invoice.amount}}
              </p>
            </div>
          }
        </div>
        <div class="flex items-center pb-2 pt-6">
          <span class="material-symbols-outlined ml-2 text-sm text-gray-500">
            sync
          </span>
          <h3 class="ml-2 text-sm text-gray-500 ">Updated just now</h3>
        </div>
      </div>
    </div>
  </div>
}
@else {
  <app-skeleton type="LatestInvoicesSkeleton"/>
}
