// 07-docker/angular-prod/order-client/src/app/components/order-form/order-form.ts
import { Component, Input, WritableSignal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Position } from '../../models/Position';
import { Server } from '../../services/server';
import { Order } from '../../models/Order';

@Component({
  selector: 'app-order-form',
  imports: [FormsModule],
  standalone: true,
  templateUrl: './order-form.html',
  styleUrl: './order-form.css'
})
export class OrderForm {
  @Input() orders!: WritableSignal<Order[]>;

  customer: string = '';
  positions: Array<Position> = [ {
      nr: 1,
      article: "",
      amount: 1,
      price: 0
    }
  ];

  constructor(private server: Server) {
  }

  public addPosition() {
    this.positions.push({
      nr: this.positions.length + 1,
      article: "",
      amount: 1,
      price: 0
    });
  }

  private makePosition(p: any): Position {
    return {
      nr: p.nr,
      article: p.article,
      amount: parseInt(p.amount),
      price: parseFloat(p.price)
    };
  }

  public createOrder(): void {
    let correctPositions = this.positions
      .filter(p => this.validPosition(p));

    if (this.customer !== '' && correctPositions.length > 0) {
      correctPositions = correctPositions.map(p => this.makePosition(p));

      const newOrder = {
        id: String(Date.now()),
        customer: this.customer,
        date: String(Date.now()),
        positions: correctPositions
      };

      this.server.createOrder(newOrder)
      .subscribe(order => {
        this.orders.update(arr => [...arr, order]);
        this.customer = '';
        this.positions = [{ nr: 1, article: '', amount: 1, price: 0.0 }];
      });
    } else {
      alert('Invalid order data!');
    }
  }

  private validPosition(p: any): boolean {
    return p.nr > 0
      && p.article !== ''
      && !isNaN(parseInt(p.amount))
      && !isNaN(parseFloat(p.price))
      && p.amount > 0
      && p.price > 0.0;
  }
}

// 07-docker/react-dev/order-client/src/components/OrderForm.jsx
import React, { useState } from 'react'
import './OrderForm.css'

function OrderForm({ onAddOrder }) {
  const [customer, setCustomer] = useState('')
  const [positions, setPositions] = useState([{ number: 1, article: '', amount: 1, price: 0.0 }])

  const addPosition = () => {
    setPositions([...positions, { number: positions.length + 1, article: '', amount: 1, price: 0.0 }])
  }

  const updatePosition = (index, field, value) => {
    const updated = [...positions];

    updated[index][field] = value;
    setPositions(updated);
  }

  const validPosition = (p) => {
    return p.number > 0 
      && p.article !== '' 
      && !isNaN(parseInt(p.amount)) 
      && !isNaN(parseFloat(p.price))
      && p.amount > 0
      && p.price > 0.0;
  }

  const makePosition = (p) => {
    return { 
      number: p.number, 
      article: p.article, 
      amount: parseInt(p.amount), 
      price: parseFloat(p.price) 
    };
  }

  const handleSubmit = (e) => {
    e.preventDefault();

    let correctPositions = positions
      .filter(p => validPosition(p));
    
    if (correctPositions.length > 0) {
      correctPositions = correctPositions.map(p => makePosition(p));

      const newOrder = {
        id: Date.now(),
        customer,
        date: Date.now(),
        positions: correctPositions
      };
      
      onAddOrder(newOrder);

      setCustomer('');
      setPositions([{ number: 1, article: '', amount: 1, price: 0.0 }]);
    } else {
      alert('Invalid order data!');
    }
  }

  return (
    <form onSubmit={handleSubmit} className="order-form">
      <label>
        Customer Name:
        <input
          type="text"
          value={customer}
          onChange={(e) => setCustomer(e.target.value)}
          required
        />
      </label>

      <div className="positions">
        <p><strong>Positions (name, amount, price):</strong></p>
        {positions.map((pos, index) => (
          <div key={index} className="position-row">
            <input
              type="text"
              placeholder="enter article name"
              value={pos.article}
              onChange={(e) => updatePosition(index, 'article', e.target.value)}
              required
            />
            <input
              type="number"
              placeholder="enter amount"
              value={pos.amount}
              onChange={(e) => updatePosition(index, 'amount', e.target.value)}
              required
            />
            <input
              type="text"
              placeholder="enter price"
              value={pos.price}
              onChange={(e) => updatePosition(index, 'price', e.target.value)}
              required
            />
          </div>
        ))}
        <button type="button" onClick={addPosition}>+ Add Position</button>
      </div>

      <button type="submit">Add Order</button>
    </form>
  )
}

export default OrderForm
